const express = require("express");
const { ApolloServer } = require("apollo-server-express");
const path = require("path");
const nodemailer = require("nodemailer");
require("dotenv").config();
const cors = require("cors");

const { typeDefs, resolvers } = require("./schemas");
const { authMiddleware } = require("./utils/auth");

const db = require("./config/connection");

const PORT = process.env.PORT || 3001;
const app = express();
var bodyParser = require("body-parser");
var jsonParser = bodyParser.json();

const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: authMiddleware,
});

server.applyMiddleware({ app });
app.use(cors());
app.use(bodyParser.json());

app.use(express.urlencoded({ extended: false }));
app.use(express.json());

if (process.env.NODE_ENV === "production") {
  app.use(express.static(path.join(__dirname, "../client/build")));
}

app.get("*", (req, res) => {
  res.sendFile(path.join(__dirname, "../client/build/index.html"));
});

app.post("/send", function (req, res, next) {
  console.log(req, "hello!");
  var transporter = nodemailer.createTransport({
    host: "smtp.mailtrap.io",
    port: 2525,
    auth: {
      user: process.env.AUTH_USER, //generated by Mailtrap
      pass: process.env.AUTH_PASS, //generated by Mailtrap
    },
  });

  var mailList = `${req.body.formState.email}, tailordepartment@tailorthrift.com`;

  const message = `Hi ${req.body.formState.firstName}. Welcome to Tailor Thrift Online Ordering! We look forward to assisting you with all of you dress apparel and tailoring needs!  We have your information recorded in the system as follows.
    Name: ${req.body.formState.firstName} ${req.body.formState.lastName}
    Email: ${req.body.formState.email}
    Measurements:
      Chest:  ${req.body.formState.chest}
      Arms:   ${req.body.formState.arms}
      Waist:  ${req.body.formState.waist}
      Inseam: ${req.body.formState.inseam}

    Please let us know if you notice any discrepancies with your information provided. 

Thanks,
The Tailor Thrift Team`;
  console.log(message);
  const mailOptions = {
    from: `hello@tailorthrift.com`,
    to: mailList,
    subject: `${req.body.formState.firstName} welcome to Tailor Thrift!`,
    text: `${message}`,
    replyTo: `hello@tailorthrift.com`,
  };
  transporter.sendMail(mailOptions, function (err, res) {
    if (err) {
      res.json({
        status: "fail",
      });
    } else {
      console.log(mailOptions);
      console.log("== Message Sent ==");
      res.json({
        status: "success",
      });
    }
  });
});

db.once("open", () => {
  app.listen(PORT, () => {
    console.log(`API server running on port ${PORT}!`);
    console.log(`Use GraphQL at http://localhost:${PORT}${server.graphqlPath}`);
  });
});
